apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: { app: mlflow }
  template:
    metadata:
      labels: { app: mlflow }
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          # Store runs DB in /mlflow/backend.db and artifacts in /mlflow/artifacts
          command: ["mlflow"]
          args:
            [
              "server",
              "--host","0.0.0.0","--port","5000",
              "--backend-store-uri","sqlite:////mlflow/backend.db",
              "--default-artifact-root","file:/mlflow/artifacts",
              "--serve-artifacts"
            ]
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: default
spec:
  type: ClusterIP
  selector: { app: mlflow }
  ports:
    - port: 5000
      targetPort: 5000
