apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  accessModes: ["ReadWriteOnce"]    # or ReadWriteMany if your storage supports it
  resources:
    requests:
      storage: 10Gi